### ISSUE TITLE
Add macOS shortcuts to move to beginning/end of file

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#125]
`Cmd+up/down` shortcuts should do this on macOS. (`Ctrl+Home/End` already work on Windows)
Should also work with `Shift` to select to beginning/end

**Comment by srjfoo** [comment]
Backward/forward a word: the default doesn't consider an apostrophe to be a word charaacter, but `option`+`left`/`right arrow` moves backward/forward a word; add shift, and it selects the word. The interveing space is selected only if you select more than one word.

`Option`+`up`/`down arrow` moves up/down a paragraph, where a paragraph is delineated by a blank line. Add shift, and it selects that text; The difference being that downwill select the blank line following a "paragraph", and up willl not.

**Comment by srjfoo** [comment]
I forgot to mention, `cmd`+`left`/`right arrow` default to beginning/end of line.

**Comment by windymilla** [comment]
Notes: [Tcl variables determine word characters](https://tcl.tk/man/tcl8.6/TclCmd/tclvars.htm#M41)

**tcl_wordchars**
The value of this variable is a regular expression that can be set to control what are considered “word” characters, for instances like selecting a word by double-clicking in text in Tk. It is platform dependent. On Windows, it defaults to \S, meaning anything but a Unicode space character. Otherwise it defaults to \w, which is any Unicode word character (number, letter, or underscore).

**tcl_nonwordchars**
The value of this variable is a regular expression that can be set to control what are considered “non-word” characters, for instances like selecting a word by double-clicking in text in Tk. It is platform dependent. On Windows, it defaults to \s, meaning any Unicode space character. Otherwise it defaults to \W, which is anything but a Unicode word character (number, letter, or underscore).

Example of how to set Tcl variables (values are not what we want though):
https://stackoverflow.com/questions/43925112/configure-tkinter-text-widget-as-code-editor-select-words-on-doubleclick

**Comment by tangledhelix** [comment]
> Backward/forward a word: the default doesn't consider an apostrophe to be a word charaacter, but `option`+`left`/`right arrow` moves backward/forward a word; add shift, and it selects the word. The interveing space is selected only if you select more than one word.

Maybe Nigel already understands it, but just to make sure: this seems to work properly already, except for the apostrophe not being a word character. In other apps it considers both single-quote and right-curly-quote to be word characters.

> `Option`+`up`/`down arrow` moves up/down a paragraph, where a paragraph is delineated by a blank line. Add shift, and it selects that text; The difference being that downwill select the blank line following a "paragraph", and up willl not.

In other apps (e.g. TextEdit) I don't find this to be the behavior — it's as you describe, but the blank line is not selected in either direction. But GG2 is currently behaving differently, where it seems to skip to the next paragraph-begin.

**Comment by tangledhelix** [comment]
> I forgot to mention, `cmd`+`left`/`right arrow` default to beginning/end of line.

For this is working in GG2 already

**Comment by srjfoo** [comment]
> > Backward/forward a word: the default doesn't consider an apostrophe to be a word charaacter, but `option`+`left`/`right arrow` moves backward/forward a word; add shift, and it selects the word. The interveing space is selected only if you select more than one word.
> 
> Maybe Nigel already understands it, but just to make sure: this seems to work properly already, except for the apostrophe not being a word character. In other apps it considers both single-quote and right-curly-quote to be word characters.

I checked BBEdit (which also excludes the single-quote from `option`+`left`/`right arrow` movement/selection), whereas LibreOffice, Pages and TextEdit all included it.

> > `Option`+`up`/`down arrow` moves up/down a paragraph, where a paragraph is delineated by a blank line. Add shift, and it selects that text; The difference being that downwill select the blank line following a "paragraph", and up willl not.
> 
> In other apps (e.g. TextEdit) I don't find this to be the behavior — it's as you describe, but the blank line is not selected in either direction. But GG2 is currently behaving differently, where it seems to skip to the next paragraph-begin.

My bad. I usually things in multiple apps, but this time, I only tried it initially in gg2, and that's where I saw the "next paragraph" behavior as delineated by a blank line. I went ahead just now and tried in other apps (BBEdit, TextEdit, LibreOffice, Pages), and only saw the next line behavior in the other apps.

-----

I guess the bottom line is that even those that seem to follow some kind of default behavior actually don't necessarily follow a common default behavior.

**Comment by srjfoo** [comment]
> > I forgot to mention, `cmd`+`left`/`right arrow` default to beginning/end of line.
> 
> For me, this is working in GG2 already, and so is the selection when adding `shift`

In case it wasn't obvious, ditto.

@tangledhelix, are there any other navigation shortcuts like these (using `option` or `cmd`, as opposed to the emacs key bindings) that you can think of that should be included.

**Comment by tangledhelix** [comment]
@srjfoo Since we've observed variation among apps in this discussion, I decided to look at the [Human Interface Guidelines][1] to see what they have to say on the topic. To my surprise, even the basics are not always what I expected ... for example:

[1]: https://developer.apple.com/design/human-interface-guidelines/keyboards#Standard-keyboard-shortcuts

| Key chord | Meaning |
|----|----|
| Command-Right arrow | Change the keyboard layout to current layout of Roman script. |
| Command-Left arrow | Change the keyboard layout to current layout of system script. |
| Command-Up arrow | {no definition provided } |
| Command-Down arrow | {no definition provided } |

The first two are totally unfamiliar to me. I'm guessing they kick in if you use e.g. both Roman and Cyrillic keyboards.

In any case, to answer your question, I can't think of any others. Perhaps `PageUp`, `PageDown`, `Home`, `End` with the obvious interpretations. My keyboard doesn't have those so I can't test what GG2 does; it may already handle them correctly.

**Comment by srjfoo** [comment]
A decade or so ago (I think, but I didn't go look it up), `Cmd`+`space` was used to switch keyboards (I've regularly had Japanese and Greek (and now Cyrillic) enabled. At some point, Apple changed the default action for `Cmd`+`space` to be Spotlight (which annoyed me, and since they allow us to redefine certain things, that's one I set back to the way it was).

I don't have `PageUp`,`PageDown`, `Home`, `End` keys, either--I use a laptop, and Mac laptops, afaik, have never had the numpad with the extra function keys (unless the user is using an external extended keyboard).

Given our experimenting, I'm totally not surprised to see up and down with no definition provided, but that makes it easier for us.

Definitely a useful-looking chart, but some of it makes very little sense. 😁
