### ISSUE TITLE
Open/Save dialog error messages on macOS Ventura

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#145]
There is [a macOS bug in NSOpenPanel tools](https://stackoverflow.com/questions/74437765/how-can-i-stop-tkinter-from-outputting-catransaction-synchronize-called-withi) associated with Ventura (not in Monterey, and reportedly not in Sonoma?). It's not specific to GG2, but affects any Tk-based app that uses the native file open/save dialogs. Messages beginning "CATransaction..." are output to the terminal window when an open/save dialog is created, and lots of them are output if the user moves the dialog.

**Comment by windymilla** [comment]
```python
    def run(self) -> None:
        """Run the app."""

        # Save current stdout & stderr & reassign to /dev/null
        # Attempting to trap "CATransaction" error messages
        null_fd1 = os.open(os.devnull, os.O_RDWR)
        null_fd2 = os.open(os.devnull, os.O_RDWR)
        fd_save1 = os.dup(1)
        fd_save2 = os.dup(2)
        os.dup2(null_fd1, 1)
        os.dup2(null_fd2, 2)

        root().mainloop()

        # Restore fds & close
        os.dup2(fd_save1, 1)
        os.dup2(fd_save2, 2)
        os.close(null_fd1)
        os.close(null_fd2)
        os.close(fd_save1)
        os.close(fd_save2)

```

**Comment by srjfoo** [comment]
No, I'm not seeing it in Sonoma.

At some point, when we're closer to a public testing release, it might be worth querying those who are interested in testing (or eventually moving to) gg2 to see if any of the Mac users are still using Ventura, since, as time goes by, fewer and fewer Mac users wil likely be using Ventura. It may ultimately be best to document it as a known issue in the command line tools for Ventura that does not affect the operation of gg2 at all.

**Comment by srjfoo** [comment]
I've thought about this for a while. At this point, I'd be perfectly happy to just warn those who use Ventura that they will likely see this, and that it's a documented issue with XCode/Command Line Tools in Ventura, but that it is not seen in other versions of the OS. If we get it back in the next version of the OS, we may have to re-think that, but I don't see this as a high-priority item.

**Comment by windymilla** [comment]
Your wish is my command ;)
