### ISSUE TITLE
Clicking on highlighted line in a report window does not bring GG main window to screen if it's minimised

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts-py#180]
I'm not sure what should be the behaviour when the GG main window is minimised and you click on a highlighted line in a report.

If the main GG window is minimised (not displayed on the computer screen) then I would expect the main GG window to be at least restored and probably brought to the fore. 

I note that if both the report window and GG main window are displayed, clicking on a highlighted line in the report brings the report window to the fore and highlights the appropriate part of the file line in the main GG window. In this situation I expected that clicking on a highlighted report line would bring the main GG window to the fore with the file line highlighted.

**Comment by windymilla** [comment]
I definitely agree with the first part - the main window should be un-minimized.

The second issue is complicated by the differing behavior of different platforms. @srjfoo, @tangledhelix and I discussed this after my first draft of the checkerdialog, which did force focus to the main window. See #157, particularly @tangledhelix comment beginning "My test results". One problem, as I understand it, is that on macOS if the focus transfers to the main window so the focus is not on the checker dialog, then a right click on the checker dialog (to remove that error) gets intercepted by the operating system.  Mac users have to put up with some similar issues in GG1 - the way that focus and mouse-clicks are processed is different from the way it happens on Windows.

I can think of some options:

1. Make the focus-switching behavior OS-specific
2. Make the focus-switching behavior a user preference (probably defaulting differently for different OSes)
3. Investigate using right-button release instead of press, in case that makes a difference. 
4. Make it work like GG1 (and say "tough luck" to Mac users)
5. Leave it like it is in GG2 (and say "touch luck" to WIndows users)
6. Investigate what happens on Linux, whichever of the above is chosen.
