### ISSUE TITLE
Maximizing doesn't store main window position properly

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#302]
This bug is in GG1 too:

On Windows at least, if you do the following, you won't get what you expect:
1. Ensure main window is not maximized.
2. Resize window so it's about half the screen size in both directions.
3. Position window away from the top-left corner of the screen, e.g. put the top-left of the window near the center of the screen.
4. Maximize window
5. Quit GG
6. Restart GG

GG will have its top-left in the position you located it in step 3, but will have its size at the maximized size (so some of the window goes off the right & bottom of the screen. 

It's pretty obvious in this case, but less obvious if the offsets are smaller, e.g. a user complained their status bar vanished off the bottom, cause by this bug.

NTS: See if it's possible to intercept/control maximizing - could store maximized flag in GGprefs, and make sure the position & size are the non-maximized values, and when GG starts, maximize if it was maximized on exit. If not, then maybe if maximized, force position to (0,0). Or (worst option), don't store size when maximizing & document that maximizing doesn't work well (on Windows) and explain how to resize window so it's more or less maximized without using the maximize button.

**Comment by srjfoo** [comment]
Tested on macOS Sonoma: On restart at step 6, the maximized window is properly positioned at the top left of the screen, but GG does seem to have lost the original (pre-maximized) size of the screen, and pre-maximized position of the top left corner of the window, because when I un-maximize, the window has been repositioned at the top left, and resized to show about 9 or 10 characters (at 14 point/pix (the setting doesn't say which unit is used), and about 9 lines.
