### ISSUE TITLE
WF hyphens check doesn't find everything GG1 does

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#304]
Reported via Slack:

> The "Word Frequency" tool in Tools only finds hyphenated pairs (to-day) and unhyphenated pairs (to-day). This feature in GG1.6 requires manual selection in preferences. We should consider adding a search for single words (today) matching hyphenated (to-day) pairs.

**Comment by windymilla** [comment]
@okrick: the hyphens tool reports the following situations:
If the file contains "to-day", then it also looks for "to day" and "today" and reports them all.
Can you check again, and give a specific file/example if there is something that is not working the way it should - thanks.

**Comment by okrick** [comment]
It works both ways for the file I'm currently working on.  So that part is OK.

Nonhyphenated words are flagged as suspect by the word frequency hyphens checker, but generally speaking, modern English leans towards omitting hyphens. For example, "blackish brown" is preferred over "blackish-brown," and "today" is more common than "to-day." My experience suggests a slightly more hyphenated style prevailed in 19th century English. However, even within that era, it seems the non-hyphenated versions were more frequent in most cases.  

- Therefore to respect the author's presumed preference, the less frequent version (likely the hyphenated one) should be flagged as suspect. In case of a tie, the hyphenated version can be considered suspect.

- Alternatively, the hyphenated version could be marked as suspect, never the nonhyphenated versions.

**Comment by windymilla** [comment]
In GG1, I think the behavior is correct. If a word appears as hyphenated AND non-hyphenated, then it is a suspect, and both forms are flagged with `****`. Following your comment, I discovered a bug in GG2, and have hopefully fixed it to behave the same as GG1. Thanks

**Comment by srjfoo** [comment]
> In GG1, I think the behavior is correct. If a word appears as hyphenated AND non-hyphenated, then it is a suspect, and both forms are flagged with `****`. Following your comment, I discovered a bug in GG2, and have hopefully fixed it to behave the same as GG1. Thanks

Tested in latest update:
<img width="1063" alt="image" src="https://github.com/DistributedProofreaders/guiguts-py/assets/36800239/bc131ace-a1bb-404c-9177-aa26d1db2b85">

That's what I expect to see with suspects not checked -- everything listed. I realize now, though, that I haven't tested completely. I got derailed by the difference between GG1 and GG2 at this stage.
