### ISSUE TITLE
The Tools=>Unmatched=>Block Markup doesn't work like GG1

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#319]
The Unmatched Block Markup misses nested blocks.

For example:
```
/#
A paragraph

/#
Another paragraph.
#/ 
#/
```
Does not appear in the report.  The nested sections usually require different formatting than the outer section.

[history_ii_5-src.zip](https://github.com/user-attachments/files/16103022/history_ii_5-src.zip)

**Comment by okrick** [comment]
By the way, the Unmatched Brackets does work correctly. The tool found nested brackets in this same file:

`[Edmund Munro of Lexington, Mass. [1736-1778], lieutenant in the French and Indian...]`

**Comment by windymilla** [comment]
Thanks for reporting that @okrick.

I've just checked your mini example, and your history_ii_5 file in GG1. 
GG1 does not report nested blockquote `/#` markup, but does report some nested markup, e.g. `/*`.
The reason is that nesting `/#` is legal, and often is what comes from the formatters. If Guiguts is used natively to do the rewrapping of the text file, and to generate the HTML, then the nested blockquotes are indented as you would expect, 
e.g. 2 spaces for the outer quote, and 4 spaces for the nested quote.
I understand that since you are using Guiguts to create a ppgen file, you may need to mark the blockquotes up with the indentation you require. However, for most users, the GG1 (and GG2) behavior is what is wanted.

As you noted, unmatched nested square brackets are reported - these are a case where the PPer probably wants to check that it is not because of square brackets inside some Footnote markup, which would break things, so again, I think the behavior is what is needed.
 
Since the behavior is intended, (and desirable for most users) I'll close this issue, unless you convince me otherwise :)

**Comment by okrick** [comment]
The issue isn't related to nesting levels or font sizes. Hanging indent sections act as the main container here. The content within these sections consists of regular paragraphs, each indented to align with the hanging section's last line. Ideally, these sections wouldn't be nested with /# ... #/ markup, but that's the current preferred approach.

**Comment by windymilla** [comment]
Thanks, Rick. I can see there could be value in a feature to find nested markup, but I don't think "Unmatched Block Markup" is the place for it, for the reasons I mentioned:
1. GG1 doesn't flag nested blockquotes
2. Default wrapping and HTML generation cope with nested blockquotes
Another possible solution would be for the various "unmatched..." options to be in a dialog, not a submenu. That dialog could then have a "Allow nesting" flag, which to apply to any of the searches.

I'll close this for now, since matching GG1 behavior is important at the moment. We can consider the other possibilities in the future, in a different issue.
