### ISSUE TITLE
GG2 needs a license

### ISSUE THREAD

**Issue by cpeel** [DistributedProofreaders/guiguts-py#32]
For developers to have confidence contributing to this repo it should have a license. Which license is up to @windymilla as the primary author and as the only other contributor thus far I hereby retroactively accept whatever [open-source license](https://opensource.org/licenses/) he uses.

I am not a lawyer, nor do I play one on TV or the internet, but if we intend to lift code from GG1 we are probably incentivized to make GG2 use the same license. That said, if we intend to **bundle** other code in a GG2 distribution that code will need to be using a compatible license. If we merely **use** other code (for instance, if we use `ebookmaker` as a python dependency but we do not bundle the `ebookmaker` code with GG2) we do not need to have compatible licenses as we are not redistributing the code. I think. To reiterate: I am not a lawyer.

Possibly-useful information:
* [Guiguts 1.x](https://github.com/DistributedProofreaders/guiguts/) uses GPLv2
* [dproofreaders](https://github.com/DistributedProofreaders/dproofreaders) uses GPLv2
* [jeebies](https://github.com/DistributedProofreaders/guiguts/blob/master/tools/jeebies/jeebies.c#L10) uses GPLv2
* [bookloupe](http://www.juiblex.co.uk/pgdp/bookloupe/) uses GPLv2
* [ebookmaker](https://github.com/gutenbergtools/ebookmaker) uses GPLv3
* `ppvimage.pl` - unknown, we should reach out to Roger
* [tidy](https://github.com/htacg/tidy-html5/blob/next/README/LICENSE.md) uses custom license
* [pptext](https://github.com/DistributedProofreaders/pptext) uses MIT

**Comment by tangledhelix** [comment]
While working on an attempt to create a macOS `.app` version of Guiguts, I did some analysis on this question. **I am not a lawyer**, but my research turned up no concerns about licensing for the various things I planned to bundle.

The below is from my notes. I've taken a few things out because some were Perl itself, or Perl modules, and wouldn't apply to a Python project.

# Licenses found
- Homebrew: BSD-2-Clause
- Homebrew (vendored): MIT
- berkeley-db: AGPL-3.0-only
- openssl@1.1: OpenSSL
- ca-certificates: MPL-2.0
- gdbm: GPL-3.0-or-later
- Guiguts: GPL 2 (only?) - may need relicensing. see below.
- bookloupe: GPL 2 (only?) - may need relicensing. see below.
- aspell: LGPL-2.1-only
- tidy-html5: Zlib
- open-sp: can't determine? all the links are 404. seems super super abandoned.
- jeebies: GPL v2+
- ebookmaker: GPL 3
- Python 3 (for ebookmaker): PSF license
- Cairo (for ebookmaker): LGPL-2.1 or MPL-1.1
- Noto Sans font: SIL Open Font License
- Java: no, I'm not dealing with this. user can do this on their own if they want.

The GPL is the most viral of all these licenses.

## BSD-2-Clause

https://opensource.org/licenses/BSD-2-Clause

- must include the license in either source or binary distribution

## MIT

https://opensource.org/licenses/MIT

- must include the license in either source or binary distribution

## AGPL-3.0

https://opensource.org/licenses/AGPL-3.0

- must include the license in either source or binary distribution
- must disclose source
- must include install instructions

# Dual OpenSSL / SSLeay license

https://www.openssl.org/source/license-openssl-ssleay.txt
# - must include the license in either source or binary form
# - must include this notice:
#  "This product includes software developed by the OpenSSL Project
#   for use in the OpenSSL Toolkit (http://www.openssl.org/)"
# - If this package is used in a product, Eric Young should be given
#   attribution as the author of the parts of the library used.
#
# MPL 2.0 [ca-certificates]
# https://opensource.org/licenses/MPL-2.0
# - Must include the license in source or binary form
# - must link to source code for original
#
# LGPL 2.1 [aspell, cairo]
# https://opensource.org/licenses/LGPL-2.1
# - must include original source, or link clearly to where to obtain it
# - must include the copyright/license
# - must give prominent notice that LGPL'd software is being used
#
# Zlib [tidy-html5]
# https://opensource.org/licenses/Zlib
# - must include copyright & license
#
# SIL Open Font License [Noto Sans font]
# http://scripts.sil.org/OFL
# This seems to be a very liberal license with almost no requirements other
# than you can't sell the fonts as a product themselves; only a product that
# includes them.
#
# PSF license [Python]
# https://docs.python.org/3/license.html
# Says it's GPL compatible. Doesn't seem to be a notification requirement
# but it's probably smarter to just include a copy of the license.
# BUT
# There are other bundled licenses; some do require notice. See the list here:
# https://docs.python.org/3/license.html#otherlicenses
#
# GNU General Public License 2.0
# https://opensource.org/licenses/GPL-2.0
# - must include/link to original
# - include copyright & license
#
# GNU General Public License 3.0
# https://opensource.org/licenses/GPL-3.0
# - must link to/include original
# - must disclose source
# - must include license/copyright info
# - must include install instructions
#
# On multiple licensing with GNU GPL
# https://en.wikipedia.org/wiki/GNU_General_Public_License#Compatibility_and_multi-licensing
#
# License TODOs?
# - [x] relicense Guiguts as GPL 2.0 "or later"? -- NO NEED,
#       guiguts.pl right at top of file has the "or later"!
# - [x] relicense bookloupe as GPL 2.0 "or later"? -- NO NEED,
#       the license embedded in the code files has "or later"!

**Comment by tangledhelix** [comment]
Just to clarify - my project was planning to bundle / distribute all of this stuff. How much of it matters will depend on how the code is packaged (or not).
