### ISSUE TITLE
Can we have the internal viewer remember the image file directory?

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#328]
When using the Auto Img internal viewer, I must select a directory whenever I open a file. In contrast, GG1 automatically opens file directories ending in "...images" from the same folder as the text file I'm editing. Additionally, GG1 only prompts me once for clarification if there's no "...images" directory.

**Comment by srjfoo** [comment]
I'd like to see this, too. As of right now, gg2 looks for the `pngs` directory in the same directory that the text file is in. If it's there, and you have `auto img` on, it opens automatically.

If you're not getting a prompt, you should be able to bring up the menu by going to `File -> Project -> Scan image directory...`.

**Comment by okrick** [comment]
GG1 can handle both `...images` and `pngs` directories for images. No need to rename anything! Thanks for reminding me about the `pngs` option though.

**Comment by srjfoo** [comment]
> BTW, the GG2 menu path is `File -> Project -> Set Scan Image Folder`

Interesting. Yes, I did forget the "Set", but my menu item is `Set Scan Image Directory...` and yes, that's just for the pngs.

I would expect choosing the images directory to be part of implementing Issue #52.

**Comment by okrick** [comment]
Thanks for pointing out . I completely missed it - I must have skipped "scan" while typing in the path.  

[#52](https://github.com/DistributedProofreaders/guiguts-py/issues/52) looks like it's on the next page of open issues, and while it doesn't directly address this specific problem, it's good to be aware of.

**Comment by windymilla** [comment]
:) I made it say "Folder" on Windows, and "Directory" on Macs, to try to make it friendlier for users of different platforms.

**Comment by tangledhelix** [comment]
> :) I made it say "Folder" on Windows, and "Directory" on Macs, to try to make it friendlier for users of different platforms.

FWIW, "Folder" is the term macOS uses (e.g. the Finder menu "File → New Folder") so we may not need to differentiate the terminology for that reason...

**Comment by windymilla** [comment]
Oops - I'll change it so that only Linux says "Directory". 
I wrote a function to return the string, but in checking on it now, I realize I didn't use that function for the menu entry, but duplicated the same "if windows..." code. 😊

**Comment by srjfoo** [comment]
😁 -- either way works for me. Who knew that "folder" would become synonymous with "directory"?

**Comment by windymilla** [comment]
I can cope with either too - if you've worked on different platforms, you quickly find out people call them by different names, but for "mono-OS" people, it would be nice to avoid them having to think about what a menu entry means.

**Comment by windymilla** [comment]
> When using the Auto Img internal viewer, I must select a directory whenever I open a file. In contrast, GG1 automatically opens file directories ending in "...images" from the same folder as the text file I'm editing. 

Thanks @okrick - I never knew that. All the hundreds of projects I've PPVed, I've never put the "projectid_images" folder inside the folder containing the text file - I've always put it parallel, because I downloaded the images zip and the PPer's uploaded text zip into a project folder, and unzipped them both, which makes sense for PPVing. Not only that, but believe it or not, the mechanism you describe relies on there being a `project_123456_comments.html` where it extracts the projectID from (`project_123456`) and the folder it then looks in is `project_123456_images`.

As Sharon mentioned, GG1 & GG2 also have subfolder `pngs` as a default. I'll implement the GG1 mechanism described above so that it works in GG2, i.e. if `pngs` doesn't exist, then it looks for a name based on the projectID (from the project comments file) with `_images` appended. Thanks for spotting & reporting that.

> Additionally, GG1 only prompts me once for clarification if there's no "...images" directory.

GG2 should work in a similar way to GG1, I think. If you try to use AutoImg and you haven't got the scans directory set to a valid directory, it will prompt you for one. You must do a "Save" to save the project "bin" file (.json file in GG2) or next time you start GG1/GG2 and load the same project, it still won't know where to find them, and will prompt again. I think this is the same in GG1 & GG2, and it needs to work that way, really. If you don't think this paragraph describes what happens in GG1 or GG2, please could you give a set of instructions that show the problem you're describing - thanks.

**Comment by okrick** [comment]
I completely missed that the `.bin` file in GG1 only gets created when the file is saved! I'm so used to auto-save happening every 5 minutes that I never even thought about it.

The comments file reference makes sense now that you mention it. Since I rename the working file, GG1 wouldn't know where to look for the image directory if it used the working file name.

Absolutely agree! Having the auto-image default in GG2 function the same way as GG1 would be a big improvement. After 10+ years of using GG, this old dog would appreciate not having to rename the image directory every time!

**Comment by srjfoo** [comment]
Does this mean also not having to sort the `_images` directory into `pngs` and `images`?

Granted, the PPer will need an `images` directory, eventually, but only for prepped illustrations.

**Comment by okrick** [comment]
Yes, once the images are prepared.  But I don't bother removing the unprepared illustrations from the `projectID64ea35d7c72db_images` directory.
