### ISSUE TITLE
Tools->Basic Fixup shift click does not work

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#344]
1. Right or Left Clicking on an entry with the Shift key, as indicated by the hover text, has no effect. The hover text currently states "With Shift key: Also remove/fix all matching issues."

2. To clarify the intended action, the hover text should be changed to "Shift Right-click: Also remove/fix all matching issues."

**Comment by windymilla** [comment]
Do you mean you were trying to use the Left & Right shift keys to click on the items in the list?
If not, I don't think I understand what you are saying, because you say "Right...clicking...with the Shift key...has no effect." in point 1, but in point 2, you say the hover text should be "Shift Right-click..."

The reason the hover text is worded like that is that it needs to be a brief reminder for the user - it's not intended to be a manual entry -  and there are lots of options:
Left click - select
Right click - remove
Ctrl left click - fix & select
Ctrl right click - fix & remove
Shift right click - remove all matching errors
Shift Ctrl left click - fix all matching errors (& select the one you clicked)
Shift Ctrl right click - fix and remove all matching errors.

The hover text is attempting to say briefly "left = select, right = remove, Ctrl = fix, Shift = matching" and they can be used in any combination that makes sense.

**Comment by okrick** [comment]
Sorry, I misunderstood what the hover text is saying.  By the way, I used a hyphen in "Shift Right-click" to indicate that Shift modified "Right-Click" instead of using the right shift key and then clicking.

Closing
