### ISSUE TITLE
Issues with Tools -> Unmatched -> Block Markup

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#349]
1. "/F" is currently flagged as unmatched block markup even when it appears mid-line, as in the following example:

`Badly formed markup: say, there it is printed in Roman, i. e.[**without space?/F1] in`

It might be helpful to limit error highlighting to instances where "/F" occurs at the beginning of a line or within a few characters of a new line.

2. The current green highlighting for "/F" in error messages is difficult to discern. I recommend using red highlighting for better visibility.

**Comment by okrick** [comment]
Additionally, highlighting alone may not be sufficient for users with color blindness. To ensure accessibility, consider incorporating additional emphasis techniques such as bolding or underlining anywhere color emphasis is used.

**Comment by windymilla** [comment]
Thanks Rick. 
1. I'll look into that - hopefully shouldn't be difficult to fix.
2. Having done a quick experiment, I see that all I was doing for the `/F` was making the text a greenish-blue, and leaving the background unchanged, but it's much more noticeable if I make it like selected text in the main window. On Windows, that defaults to white text on a blue background. This is much more noticeable, even without seeing the colors, because the background color is changed, not just the text color. I experimented with underlining (bolding isn't practical) but it makes it very busy in addition to the background color change. So, I suggest I just make the above change to match the main text selection colors, and we see if that's acceptable.

**Comment by windymilla** [comment]
@okrick - I now see why I was surprised at point number 1. 
In fact, the unmatched markup error message will only occur if the markup is at the start of a line.
The error message you are getting is "Badly formed markup", not "Unmatched".  The "Badly formed" error will appear if something looks like markup, but is in the wrong place, or doesn't have the correct format, e.g. `/#[25.1O]` (that's a letter O that should have been a zero).
The reason I added that extra check, is that faulty markup could mean that the unmatch check gave surprising errors that were harder for the user to track down, and/or two errors could cancel each other out so that the user didn't get warned at all. Here's an example from when I added the feature:
```
/#
text
/#[bad markup]
even more
more text (note space before close markup below, which invalidates it)
 #/
final text
#/
```

We will need to make sure the manual describes those two error types, to avoid confusion for the user. I know it won't happen often, and with the improved highlighting, it should be clearer to the user what the problem was - in your case, the `/F1`

**Comment by okrick** [comment]
I agree.  I was looking for markup issues and overlooked the slash without an accompanying "<" as a concern.

**Comment by windymilla** [comment]
Excellent - I've improved the highlighting, and put that up for testing, so it should be in the next release.
