### ISSUE TITLE
Tools->Unmatched DP Markup odd report

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#359]
```
/*
<lang=it>O vedovate da perpetuo gelo
Terre, e d’incerto di mest sorriso,
Addio!\_*\_*\_* Questo petto anelo
Scosse di gioia un palpito improvviso,
Quando il Tiranno splendido del cielo
Mi rivelò d’ Italia il paradiso.--<sc>Niccolini.</sc></lang>
*/
```
The DP Markup popup displays only `Unmatched: </lang>`. The `<lang=it>...</lang>` tag is a ppgen function. While I expected an outcome, it's inconsistent. Either both tags should have been reported as unmatched, or neither should have appeared.

**Comment by windymilla** [comment]
At the moment, the tool supports all DP Markup, which is always of the form `<xxx>...</xxx>` with no equals signs.
It does this by allowing any letters between the `<` (or `</`) and the `>`, and the two such groups of letters must be identical.

If I understand correctly, then you would have accepted if it had ignored `lang` completely because it is not DP markup. Or you would have accepted it recognizing `lang` as long as it also accepted `lang=it`.

One way to do the first, would be to have a specific list of DP markups that are checked, rather than allowing any word made entirely of letters.
One way to do the second, would be to ignore additional characters after the first word - in this case, ignore the `=it` that follows the `lang`.

Although I guess it would be most helpful for ppgen users to do the second of these, there is more complication involved. I believe all the following are valid in ppgen markup: `<lang=it>` as we've mentioned, `<abbr rend=arabic>...<\abbr>`, and maybe  some more where there is a closing markup that matches the first word of the opening markup. There are also cases where no closing markup is required, but the ppgen command is indistinguishable from opening markup, e.g. `<al=c>`, `<pm mymacro arg1 arg2>`, etc. I think it's also the case that a ppgen file can contain arbitrary HTML, which again could have a range of matched or non-matched tags.

@okrick - because of the above issues, do you think it would be acceptable to limit the unmatched DP markup check to the markup that is permitted to come from the DP rounds: `i`, `b`, `u`, `g`, `f`, `sc`?

**Comment by okrick** [comment]
I agree, that would be acceptable.
