### ISSUE TITLE
Tools->Word Frequency Control-left click Search & Replace highlighting

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#373]
When using Hyphens mode, clicking a word or phrase with Ctrl+Left Click opens the "Search & Replace" dialog. The selected word appears highlighted in the "Search" field, mimicking selection. However, pressing Ctrl+C doesn't copy the term. You need to re-select it manually before pasting it into the "Replace" field.

Ideally, the highlighted term should be automatically selected, allowing immediate copying with Ctrl+C. If this can't be achieved, perhaps removing the highlight altogether when opening the dialog via Ctrl+Left Click in Word Frequency would be a better solution.

Interestingly, when a word or phrase is selected in the editing area and Ctrl+F is used, the search term is highlighted as expected. Unlike the behavior in WF, the highlighted term can be copied directly using Ctrl+C without needing to reselect it.

**Comment by windymilla** [comment]
Thanks for that. 

Slight clarification to the description after investigating...
1. There is definitely a bug, which needs fixing.
2. The bug doesn't show on the very first use of this instance of the dialog, i.e. when the S/R dialog has never been used, or has been dismissed, and the Ctrl-click in WF is re-popping it.
3. The problem occurs when the focus in the S/R dialog that pops up is not in the Search box, but elsewhere (actually nowhere) in the dialog. Using the tab key will show the focus swap between the Search & the Replace, but when the dialog gets used for a second time (without being dismissed), it appears as though the focus is in neither search nor replace. This means that although the search term is selected, the Ctrl-C does not go to the Search field, so it doesn't copy the text.
4. Should be fairly easy to fix - when Ctrl-click pops the S/R dialog, it should make sure the focus is in the Search field after it fills the field and selects it.
5. NTS - check to see what happens when S/R is triggered from the main window with Ctrl-F on a selected word, but the S/R dialog was already visible, and focus was in the Replace field.
