### ISSUE TITLE
Search->Search & Replace Count doesn't count some things

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#396]
I used the regular expression `([\*#])/\n(\-[^\n]+[\-\\]\n+)/\1\n` to search for a specific pattern and replace it with `\2`. With 'Wrap-around' and 'Regex' options enabled, the 'Count' function reported `Found: 0 matches in entire file.` However, the correct number of matches should have been 3.
[fan-src.zip](https://github.com/user-attachments/files/16715567/fan-src.zip)

**Comment by okrick** [comment]
By contrast, `/\*((\n|.)+?)\*/` counts 21 matches.

**Comment by windymilla** [comment]
@okrick - I discovered the reason. There's a bug in the regex module, which I've reported to them (though I don't know if it will get fixed). The bug is that if you use a backreference like your `\1` and search backwards, it will not find a match. You can confirm this by doing a normal search and finding the 3 matches, then clicking the "reverse" checkbox and trying to search again.

If you replace `\1` with `[\*#]` (or do the two searches for `/*` and `/#` separately), then Count, Search forward or backward will work.

For simplicity of coding reasons, I made Count (and Replace All) search backwards through the file, so it hits this bug.
I'll attempt to code it to search forwards, and for now at least, we'll have to document that you can't Search backward for regexes with a backreference.
