### ISSUE TITLE
Make one-line change to 'Footnote Fixup' code

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts-py#431]
There is a bug in 'footnotes.py' which has a simple, one-line, fix. It is in the block of code from lines 157-168 that finds the colon position in the tag, or uses end of the word "Footnote".

The bug doesn't manifest itself in 'Footnote Fixup' because all footnote tags that it processes have a ':' at some point after the string 'Footnote; that is, you should only see the forms '[Footnote 9: text.]' or '*[Footnote: text.]' when processing a file. This means the faulty code is never exercised.

However, when you use the same code in another module to parse an '[Illustration]' tag (note no ':' in the tag), the string 'Illustration' is not highlighted in the dialog because the calculation to find the end of the string 'Footnote' or 'Illustration', etc., is incorrect. The fix below corrects it. 

Current Code:
```
            start = beg_match.rowcol
            # Find colon position, or use end of the word "Footnote"
            colon_match = maintext().find_match(
                ":", IndexRange(start, maintext().rowcol(f"{start.row}.end"))
            )
            if colon_match is None:
                colon_pos = maintext().rowcol(
                    f"{start.index()}+{beg_match.count + 1}c wordend"
                )
            else:
                colon_pos = colon_match.rowcol
            end_point = colon_pos
```
Replace 8th line down (line 164) with
`                    f"{start.index()}+{beg_match.count}c"`

**Comment by windymilla** [comment]
I put up a PR to fix this, but during testing and subsequent reflection, I realised that the original code did what I had intended, so I have closed the PR.

The original `f"{start.index()}+{beg_match.count + 1}c wordend"` means that in the case of a missing colon, the selection continues to the end of the first word after `Footnote`. This is so that cases like `[Footnote 7 - A note]` or `[Footnote 7 A footnote]` still select `Footnote 7` even without the colon to show the end of the footnote number/letter. 

With the suggested edit, just `Footnote` is selected, which I think is less helpful to the PPer. The only case I can think of where the suggested code would be better is when the footnote is a continued one AND the formatters failed to include the colon after the word `Footnote`, which I think is less frequent than a regular, non-continued footnote with a missing colon. Even in this infrequent case, the results would not be serious, e.g. `*[Footnote You forgot the colon]` would select `Footnote You`, and 
`*[Footnote - You used hyphen instead of colon]` would select `Footnote -`.

If you're in agreement, @G4OEU, that for the footnote case only, the original code is OK, then either you or I can close this issue. If not, feel free to add more comments/examples.

**Comment by G4OEU** [comment]
I'm in agreement with @windymilla on this. The code in its original footnotes context works correctly. It is only when the code is used in a different context, as in 'Illustration Fixup' for example, that the fix maybe required. This issue is now closed.
