### ISSUE TITLE
Convert Fractions misses fractions at start of line

### ISSUE THREAD

**Issue by rtonsing** [DistributedProofreaders/guiguts-py#563]
If a number with fraction starts in column 0, then it is missed. Happens with both "2-1/2" and "1/2" styles, and all 3 conversion choices. Inserting a blank in col. 0 fixes the issue.

Version 2.0.0a10
Windows 11 64-bit

**Comment by srjfoo** [comment]
By "column 0", do you mean the first column on the page? (Column 0 is actually the column preceding the first character on a given line. Can you show screenshots?

macOS, using alpha-10:

Starting point:
<img width="130" alt="image" src="https://github.com/user-attachments/assets/c4809b64-5af3-448d-925f-774c7b66a4d0">


Unicode or super/subscript:
<img width="161" alt="image" src="https://github.com/user-attachments/assets/85589b6c-4109-4b38-aed9-33b534bb7b4e">


Unicode fractions only:
<img width="161" alt="image" src="https://github.com/user-attachments/assets/c001ba5c-b3a5-46d6-ab61-4e7b33a8c2b7">


All to super/subscript:

<img width="133" alt="image" src="https://github.com/user-attachments/assets/bcde37f0-dae6-4d3d-b552-5392991d3ae3">

**Comment by rtonsing** [comment]
![image](https://github.com/user-attachments/assets/020b7527-2dc4-4146-8369-f494a44048f5)

Note that although I am running 'poetry run guiguts' in a current repository, I'm not 100% sure it is really running the latest code from the repo.

**Comment by srjfoo** [comment]
Are you running the current alpha 1 release, or the development version. I tried it both ways and got the same results as in the screenshots above, so it doesn't really matter whether you're using the alpha release or the current dev `master`; that behaves the same for me. Though I did not test it with other surrounding text. I'll try that after dinner and get back to you.

**Comment by srjfoo** [comment]
Okay ... what I'm seeing now is that, if those fractions that don't have a direct unicode version are alone on a line (e.g. `23/32` or `2-3/16`) they'll be converted to super-/subscript fractions (either version of that command). In mixed text and fractions, they won't be if they're at the beginning of the line. Fractions that have a unicode version will be converted. For me, on macOS.

Screenshot is post-conversion, command used: Unicode Fractions or Super/Subscripts:

<img width="333" alt="image" src="https://github.com/user-attachments/assets/b3974453-2a58-41e0-9538-211ec197ebaf">

Tested in both developer `master` and in the alpha-10 release with identical results.

**Comment by windymilla** [comment]
What I'm seeing is slightly different - it fails to convert if there is something on the line prior to the fraction. So
```
X
23/32

```
converts correctly, but
```

23/32

```
does not

**Comment by rtonsing** [comment]
For me, if there is a preceding blank line it works, if it is not col. 0 (per status line) it works, but at the start of the line inside a paragraph, it does not.
Tried several files to make sure it is not isolated. Title line says 2.0.0a10, I do not have alpha guiguts package installed. This example used fractions with Unicode values.
![image](https://github.com/user-attachments/assets/0ba48754-0f10-477b-a9a6-aec26c870ba5)

**Comment by windymilla** [comment]
Following through the code in the debugger, it's a fault in the check to avoid converting plate/serial numbers, like `B1/2` or `C-1/3`. It gets the two characters preceding the fraction (in this case `X\n`) and checks if those match `\p{L}-` or `\p{L}$`. The first of those clearly doesn't match. By all "normal" regex rules, the second should not match either, because `$` means "end of string" and there isn't a letter at the end of `X\n`. However, in some regex flavors (including Python) a `$` can also match a newline if that newline is at the end of the string.

From [the docs](https://docs.python.org/3/library/re.html#re.MULTILINE) (my emphasis):
> By default, '^' matches only at the beginning of the string, and '$' only at the end of the string **_and immediately before the newline (if any) at the end of the string_**.

It's easy to use a different check, but this regex behavior surprised me, though it is perhaps familiar to others, since according to the table in the middle of [this page](https://sethmlarson.dev/regex-%24-matches-end-of-string-or-newline) PHP and Java behave the same as Python.

**Comment by windymilla** [comment]
Oops - I think I put my two examples the wrong way round! So exactly the opposite of what I said!! I'll go and fix that
