### ISSUE TITLE
Fraction conversion a bit too aggressive?

### ISSUE THREAD

**Issue by rtonsing** [DistributedProofreaders/guiguts-py#572]
Rather minor, but I have a book with:

4.2
----
18.2

which was proofed as "4.2/18.2".
Running Fraction Convert produced "4.²⁄₁₈.2".
An unusual case, and putting spaces around the '/' prevented it, but we can't predict what proofers will do.
GG1 does the same thing.

**Comment by windymilla** [comment]
Thanks for reporting it. 

Just checked, and Guiguts 1 does the same. But that doesn't mean Guiguts 2 should do it.
We want `one ninth is 2/18.` to be converted, i.e. with a period after the 18, but I can't think of a circumstance where we would want `.2/18` to be converted. Shouldn't be too hard to trap that case - it already checks for things like `A2/18` (which it assumes is a plate or serial number, rather than a fraction).
