### ISSUE TITLE
Some issues with Tools: Rewrap All

### ISSUE THREAD

**Issue by rtonsing** [DistributedProofreaders/guiguts-py#600]
Examples of issues, there are multiple of each:    Line # before/after

- blank line after markup removed 316/303
- 4 blank lines ==> 3 blank lines 321/307
- [Illustration: ...] joined to previous paragraph 6265/4861

I have seen these with another file, also.
[before.zip](https://github.com/user-attachments/files/18241259/before.zip)
[after.zip](https://github.com/user-attachments/files/18241260/after.zip)

**Comment by windymilla** [comment]
Thanks Robert - very helpful test file. I think/hope I've found it. Those blank lines that get lost are ones that have a page break.

Brief technical explanation:
In order to preserve page break information during wrapping, an invisible character is inserted at every relevant page break before wrapping. Then after wrapping, the page breaks are repositioned at the invisible characters before the invisible characters are removed. 
Where the code was checking for a blank line, such as after the markup on line 316, the line wasn't completely blank - it contained one of the invisible characters, so the algorithm failed to spot that it was a paragraph break, and the blank line was lost.
